title: Abubalay
author: Russell Johnston

permalink: /blog/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

kramdown:
  entity_output: symbolic

plugins:
  - jekyll-feed
