title: Abubalay
author: Russell Johnston

permalink: /blog/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
    values:
      layout: "post"

kramdown:
  entity_output: symbolic
  syntax_highlighter_opts:
    span:
      default_lang: 'rust'

plugins:
  - jekyll-feed
